// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH5ts2_X9Z2vdcH62-y-A7SqyhhIg9sAg',
    appId: '1:515325957839:android:82cf5bd376a87f3390c9ba',
    messagingSenderId: '515325957839',
    projectId: 'logintodo-a9ad0',
    storageBucket: 'logintodo-a9ad0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwDsYYrhpIlXArVh3em8cHYiZyUo0M9HU',
    appId: '1:515325957839:ios:673e88f5b153c0bc90c9ba',
    messagingSenderId: '515325957839',
    projectId: 'logintodo-a9ad0',
    storageBucket: 'logintodo-a9ad0.appspot.com',
    iosClientId: '515325957839-ginjcanhuc70c96664mv8m7p3s49ejqm.apps.googleusercontent.com',
    iosBundleId: 'com.eraasoft.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwDsYYrhpIlXArVh3em8cHYiZyUo0M9HU',
    appId: '1:515325957839:ios:673e88f5b153c0bc90c9ba',
    messagingSenderId: '515325957839',
    projectId: 'logintodo-a9ad0',
    storageBucket: 'logintodo-a9ad0.appspot.com',
    iosClientId: '515325957839-ginjcanhuc70c96664mv8m7p3s49ejqm.apps.googleusercontent.com',
    iosBundleId: 'com.eraasoft.todo',
  );
}
